accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('user_profile/',views.user_profile, name='user_profile'),

    path('',views.UserListView.as_view(), name='list'),
    path('create/',views.UserCreateView.as_view(), name='create'),

]

core/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('products/', include('products.urls')),
    path('offers/', include('offers.urls')),
    path('notifications/', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('countries.urls')),

    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'
        ),
        name="reset_password"
    ),
    path(
        'reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_sent.html'
        ),
        name="password_reset_done"
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_form.html'
        ),
        name="password_reset_confirm"
    ),
    path(
        'reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name="password_reset_complete"
    ),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html',
            success_url = '/'
        ),
        name='change_password'
    ),

]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, \
                                        PermissionsMixin

from .managers import UserManager
from countries.models import Countries

class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that suppors using email instead of username"""
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=25, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    team = models.CharField(choices=(
        ('sourcing', 'Sourcing'),
        ('sales', 'Sales'),
    ), default='sourcing', max_length=10)

    objects = UserManager()

    countries = models.ManyToManyField(Countries, related_name='users')

    USERNAME_FIELD = 'username'

    def __str__(self):
        return f"{self.id} | {self.username} | {self.team}"

accounts/views.py
from django.shortcuts import render, HttpResponse , redirect
from django.views import View
#from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, logout as dj_logout, login as dj_login
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import User

def base(request):
    if request.user.is_authenticated:
        return HttpResponse(request.user.username)
    else:
        return redirect('login')


def login(request):
    """
    REGISTER:
        GET CREATE USER FORM
        IF POST:
            GET USERNAME AND PASSWORD
            AUTHENTICATIE THE USERNAME AND PASSWORD
            IF USER FOUND: LOGGED IN THE USER AND REDIRECT TO DASHBOARD
            ELSE: RETURN THE INVALID USER FORM
                
    """
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user= authenticate(request, username=username, password=password)

        if user is not None:
            dj_login(request, user)
            redirect_to = request.session.get('redirect_to', None) # IF REDIRECT URL: MARKETED CUSTOMER
            if redirect_to:
                del request.session['redirect_to']
                return redirect(redirect_to)
            else:
                mode = 'sourcing' if user.team == 'sales' else "sales"
                return redirect(f"dashboard")
        else:
            messages.info(request,'Username Or Password is incorrect')
    context={}
    return render(request,'accounts/login.html',context)


def logout(request):
    """
    LOGOUT USER
    """
    dj_logout(request)
    return redirect('accounts:login')


def user_profile(request):
    """
    IF LOGGED IN: RETURN TO PROFILE PAGE
    IF NOT LOGGED IN: RETURN ERROR
    """
    if request.user.is_authenticated:
        context={}
        return render(request, 'accounts/user_profile.html', context)
    else:
        return HttpResponse('please login with your credentials to view user profile page ')


class UserListView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            print("Not Logged In")
            return redirect("accounts:login")

        users = User.objects.all().exclude(id=request.user.id)
        return render(request, "accounts/list.html", {
            "users": users
        })

    def post(self, request):
        user = User.objects.get(id=request.POST.get('id'))
        user.is_active = request.POST.get('is_active') == "on"
        if request.POST.get('team') == 'admin':
            user.is_superuser = True
        else:
            user.is_superuser = False
            user.team = request.POST.get('team')
        user.save()

        return redirect('accounts:list')

class UserCreateView(View):

    
    def get(self, request):
        if not request.user.is_authenticated:
            print("Not Logged In")
            return redirect("accounts:login")

        users = User.objects.all()
        return render(request, "accounts/create.html", {
            "users": users
        })

    def post(self, request):
        if User.objects.filter(
            username=request.POST.get('username')
        ).exists():
            return render(request, "accounts/create.html", {
                "error": "User with this username already exists"
            })
        else:
            user = User(
                username=request.POST.get('username'),
                email=request.POST.get('email'),
            )
            team = request.POST.get('team')
            if team == 'admin':
                user.is_superuser = True
                user.team = 'sourcing'
            else:
                user.team = team
            user.save()
            user.set_password(request.POST.get('password'))

            return redirect('accounts:list')

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}YourSite{% endblock title %}

{% block body %}

{% block content %}
<h2>Change Password</h2>
<br>
<div class="container">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'accounts:user_profile' %}">Back</a>
    <button type="submit">Submit</button>
</form>
</div>
{% endblock content %}

{% endblock body %}

{% block js %}

{% endblock js %}

templates/accounts/create.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <h1 class="text-center">Create User</h1>
    <form action="" method="post">{% csrf_token %}
        <div class="form-group">
            <label for="input_name">Username:</label>
            <input type="text" class="form-control" name="username" id="input_username" placeholder="" required>
            <small id="passwordHelpBlock" class="form-text text-danger">{{error}}</small>
        </div>
        <div class="form-group">
            <label for="input_email">Email:</label>
            <input type="text" class="form-control" name="email" id="input_email" placeholder="" required>
        </div>
        <div class="form-group">
            <label for="input_password">Password:</label>
            <input type="text" class="form-control" name="password" id="input_password" placeholder="" disabled value="abcd1234">
        </div>
        <div class="form-group">
            <label for="input_unit">Team</label>
            <select class="form-control" id="input_unit" name="team" required>
                <option value="sourcing">Sourcing</option>
                <option value="sales">Sales</option>
                <option value="admin">Admin</option>
            </select>
        </div>
        <button class="btn btn-primary col-12" type="submit">Create User</button>
    </form>
</div>
{% endblock body %}

templates/accounts/list.html
{% extends 'base.html' %}


{% block body %}

    <div class="container">
        <h1 class="text-center my-5">Manage Users</h1>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">username</th>
                <th scope="col">Email</th>
                <th scope="col">Team</th>
                <th scope="col">Active</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <form action="." method="post">{% csrf_token %}
                    <tr>
                        <th scope="row" hidden><input type="text" hidden name="id" value="{{user.id}}"></th>
                        <th scope="row">{{user.username}}</th>
                        <td>{{user.email}}</td>
                        <td>
                            <select class="form-control" id="input_team" name="team" required>
                                <option value="admin" {% if user.is_superuser %} selected {% endif%} >Admin</option>
                                <option value="sourcing" {% if not user.is_superuser and user.team == 'sourcing' %} selected {% endif%} >Sourcing</option>
                                <option value="sales" {% if not user.is_superuser and user.team == 'sales' %} selected {% endif%}>Sales</option>
                            </select>
                        </td>
                        <td>
                            <div class="custom-control custom-switch">
                                <input type="checkbox" class="custom-control-input" name="is_active" id="customSwitch{{user.id}}" {% if user.is_active %}checked{% endif %}>
                                <label class="custom-control-label" for="customSwitch{{user.id}}"></label>
                            </div>
                        </td>
                        <td>
                            <button type="submit" class="btn btn-success">Update</button>
                        </td>
                        
                      </tr>
                </form>
                {% endfor %}
                <tr>
                    <td colspan="5"><a href="{% url 'accounts:create' %}" class="col-12 btn btn-primary">Create User</a></td>
                </tr>
            </tbody>
          </table>
    </div>

{% endblock body %}

{% block js %}

{% endblock js%}

templates/accounts/login.html
{% load static %}
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<link rel="stylesheet" href="{% static 'css/login.css' %}">

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		        {% for message in messages %}
                    <p id=  "messages"> {{message}} </p>
                {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Forget your password?<a href="{% url 'reset_password' %}" class="ml-2"> Reset Now</a>
					</div>
					{% comment %}
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
					</div>
					{% endcomment %}


				</div>
			</div>
		</div>
	</div>
</body>

templates/accounts/password_reset.html
{% load static %}
<html>
  <head>
    <title>Password Reset</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
      integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
  </head>
  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <h3 id="form-title">Password Reset</h3>
          </div>
          <p id="form-title" class="mt-3">
            Forgotten your password? Enter your email address below, and we’ll
            email instructions for setting a new one.
          </p>
          <div class="d-flex justify-content-center form_container col-12">
            <form method="POST" action="">
              {% csrf_token %}
              <div class="input-group col-12 mb-3">
                <input
                  type="text"
                  name="email"
                  placeholder="email..."
                  class="form-control"
                />
              </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Submit" />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/accounts/password_reset_done.html
{% load static %}
<html>
  <head>
    <title>Password reset complete</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
      integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
  </head>
  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <h3 id="form-title">Password reset complete</h3>
          </div>
          <p id="form-title" class="mt-3">
            Your password has been set. You may go ahead and log in now.</p>
          </p>
          <div class="d-flex justify-content-center mt-3 login_container">
            <a href="{% url 'accounts:login' %}"class="btn login_btn"> LOGIN </a>
          </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/accounts/password_reset_form.html
<h3>Enter new password</h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">

</form>

templates/accounts/password_reset_sent.html
{% load static %}
<html>
  <head>
    <title>Password Reset Sent</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
      integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
  </head>
  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <h3 id="form-title">Password Reset</h3>
          </div>
          <p id="form-title" class="mt-3">
            We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
        <p id="form-title" class="mt-3">If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
          </p>

          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/register.css' %}">



</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>
						<div class="input-group mb-2">
							{{form.mode}}
						</div>

                        {{form.errors}}
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- <script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script> -->
</body>
</html>

templates/accounts/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}YourSite{% endblock title %}

{% block body %}
<div class="container mt-5">
	<div class="col-12 mt-3">
		<form method="POST">
			<div class="form-group">
			  <label for="exampleInputEmail1"><strong>Want to change your password? </strong></label>
			  <a href="{% url 'change_password' %}" class="btn btn-primary">Update Password</a>
			</div>
			<hr>
			<div class="form-group">
			  <label for="exampleInputEmail1"><strong>Email address</strong></label>
			  <input disabled type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" value="{{request.user.email}}">
			  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
			</div>
			<button disabled type="submit" class="btn btn-primary">Submit</button>
		  </form>
	</div>
</div>

<br>
{% endblock body %}

{% block js %}

{% endblock js %}