core/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

countries/urls.py
from django.urls import path

from . import views


app_name = "countries"

urlpatterns = [
    path('transportation/setup/', views.TransportationSetupView.as_view(), name='transportation_setup'),

    path('country/create/', views.CountryCreateView.as_view(), name='country_create'),
    path('country/update/<int:pk>/', views.CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<int:pk>/', views.CountryDeleteView.as_view(), name='country_delete'),

    path('region/create/<int:pk>/', views.RegionCreateView.as_view(), name='region_create'),
    path('region/delete/<int:pk>/', views.RegionDeleteView.as_view(), name='region_delete'),
    path('region/location/<int:pk>/', views.RegionLocationUpdateView.as_view(), name='region_edit_location'),

    path('region/closest/', views.ClosestRegionByCoordinatesView.as_view(), name='api_closest_region')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('products/', include('products.urls')),
    path('offers/', include('offers.urls')),
    path('notifications/', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('countries.urls')),

    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'
        ),
        name="reset_password"
    ),
    path(
        'reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_sent.html'
        ),
        name="password_reset_done"
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_form.html'
        ),
        name="password_reset_confirm"
    ),
    path(
        'reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name="password_reset_complete"
    ),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html',
            success_url = '/'
        ),
        name='change_password'
    ),

]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

products/urls.py
from django.urls import path

from . import views


app_name='products'

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='list'),
    path('create/', views.ProductsCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ProductsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.ProductsDeleteView.as_view(), name='delete'),
    path('unit/create/', views.UnitCreateView.as_view(), name='unit_create'),
]

suppliers/urls.py
from django.urls import path

from . import views


app_name='suppliers'

urlpatterns = [
    path('', views.SuppliersListView.as_view(), name='list'),
    path('create/sourcing/', views.SuppliersSourceCreateView.as_view(), name='create_by_sourcing'),
    path('create/sales/', views.SuppliersSalesCreateView.as_view(), name='create_by_sales'),
    path('create/<int:pk>/price/', views.SuppliereNewPriceCreateView.as_view(), name='add_price_by_sourcing'),
    path('edit/<int:pk>/', views.SupplierUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SupplierDeleteView.as_view(), name='delete'),  
]

suppliers/models.py
from django.utils import timezone
from django.db import models

from accounts.models import User
from countries.models import Regions
from products.models import Product

class Suppliers(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    region = models.ForeignKey(Regions, on_delete=models.SET_NULL, null=True, blank=True)

    identifier = models.CharField(max_length=50, null=True, blank=True)
    format = models.CharField(max_length=5000, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    company_name = models.CharField(max_length=1000, null=True, blank=True)
    contact_name = models.CharField(max_length=1000, null=True, blank=True)
    landline = models.CharField(max_length=1000, null=True, blank=True)
    mobile = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField(max_length=1000, null=True, blank=True)

    departure_address_lat = models.FloatField(null=True, blank=True)
    departure_address_lng = models.FloatField(null=True, blank=True)

    destination_address_lat = models.FloatField(null=True, blank=True)
    destination_address_lng = models.FloatField(null=True, blank=True)

    margin = models.FloatField(null=True, blank=True)
    weight_of_full_truck = models.FloatField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)

    price_exwb = models.FloatField(null=True, blank=True)
    price_exws = models.FloatField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.id}, {self.company_name}"

    def get_supplier_prices(self):
        return SupplierPrices.objects.filter(
            suppliers=self,
        ).order_by("-added_on", "-id")


class SupplierPrices(models.Model):
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    suppliers = models.ForeignKey(Suppliers, on_delete=models.CASCADE, related_name="supplier_prices")
    price_exwb = models.FloatField(null=True, blank=True)
    price_exws = models.FloatField(null=True, blank=True)
    added_on = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return f"{self.suppliers.company_name}, {self.added_on.date}"


class CertificationDocumentSuppliers(models.Model):
    supplier = models.ForeignKey(Suppliers, on_delete=models.CASCADE, related_name='certifications')
    file = models.FileField(null=True, blank=True, upload_to='certifications/')


class SpecificationDocumentSuppliers(models.Model):
    supplier = models.ForeignKey(Suppliers, on_delete=models.CASCADE, related_name='specifications')
    file = models.FileField(null=True, blank=True, upload_to='specifications/')

suppliers/forms.py
from django import forms

class FileForm(forms.Form):
    file = forms.FileField(widget = forms.TextInput(attrs={
            "name": "images",
            "type": "File",
            "class": "form-control",
            "multiple": "True",
        }), label = "")

suppliers/views.py
from django.shortcuts import render, redirect
from django.views import View

from products.models import Product
from countries.models import Regions, Countries
from .forms import FileForm
from .models import Suppliers, SupplierPrices, CertificationDocumentSuppliers, SpecificationDocumentSuppliers
from .utils import calculate_price_from_source, calculate_price_from_sales
from offers.utils import generate_offers, \
    generate_offers_for_new_supplier, generate_offers_for_supplier_new_price, \
    delete_offers_of_suppliers_on_supplier_delete

class SuppliersListView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            print("Not Logged In")
            return redirect("accounts:login")

        suppliers = Suppliers.objects.all().order_by('-id')
        products = Product.objects.all()
        countries = Countries.objects.all()

        selected_product_id = request.GET.get('product', None)
        if selected_product_id:
            selected_product = Product.objects.get(id=selected_product_id)
            products = products.exclude(id=selected_product_id)
            suppliers = suppliers.filter(product_id=selected_product_id)
        else:
            selected_product = None

        selected_country_id = request.GET.get('country', None)
        if selected_country_id:
            selected_country = Countries.objects.get(id=selected_country_id)
            countries = countries.exclude(id=selected_country_id)
            suppliers = suppliers.filter(region__country_id=selected_country_id)
        else:
            selected_country = None

        search = request.GET.get('search', "")
        if search:
            suppliers = suppliers.filter(company_name__icontains=search).order_by('-id')

        return render(request, 'suppliers/list.html', {
            "suppliers": suppliers,
            "products": products,
            "selected_product": selected_product,
            "countries": countries,
            "selected_country": selected_country,
            "search": search
        })


class SuppliersSourceCreateView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            print("Not Logged In")
            return redirect("accounts:login")

        products = Product.objects.all()
        regions = Regions.objects.all().order_by('country')
        fileform = FileForm()
        return render(request, 'suppliers/source/create.html', {
            "products": products,
            "regions": regions,
            "fileform": fileform
        })

    def post(self, request):
        data = request.POST
        
        supplier = Suppliers(
            product_id=data.get('product'),
            added_by=self.request.user,
            region_id=data.get('region'),

            company_name=data.get('company_name'),
            contact_name=data.get('contact_name'),
            landline=data.get('landline'),
            mobile=data.get('mobile'),
            email=data.get('email'),
            format=data.get('format'),
            comments=data.get('comments'),
            # certifications=data.get('certifications'),
            # specifications=data.get('specifications'),
            identifier=data.get('identifier'),
    
            departure_address_lat=data.get('departure_address_lat', None),
            departure_address_lng=data.get('departure_address_lng', None),
            destination_address_lat=data.get('destination_address_lat', None) if data.get('destination_address_lat', None) else None,
            destination_address_lng=data.get('destination_address_lng', None) if data.get('destination_address_lng', None) else None,
    
            weight_of_full_truck=data.get('weight_of_full_truck'),
            margin=data.get('margin'),
            price=data.get('price'),
        )

        price_data = calculate_price_from_source(data)

        supplier.price_exwb = price_data['exwb']
        supplier.price_exws = price_data['exws']

        supplier.save()

        SupplierPrices.objects.create(
            added_by=self.request.user,
            suppliers=supplier,
            price_exwb=supplier.price_exwb,
            price_exws=supplier.price_exws
        )

        for certification_document in request.FILES.getlist('certifications'):
            CertificationDocumentSuppliers.objects.create(
                supplier=supplier,
                file=certification_document
            )

        for specification_document in request.FILES.getlist('specifications'):
            SpecificationDocumentSuppliers.objects.create(
                supplier=supplier,
                file=specification_document
            )

        generate_offers_for_new_supplier(supplier)

        return redirect('suppliers:list')


class SuppliersSalesCreateView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            print("Not Logged In")
            return redirect("accounts:login")

        products = Product.objects.all()
        regions = Regions.objects.all().order_by('country')
        return render(request, 'suppliers/sales/create.html', {
            "products": products,
            "regions": regions
        })

    def post(self, request):
        data = request.POST
        
        supplier = Suppliers(
            product_id=data.get('product'),
            added_by=self.request.user,
            region_id=data.get('region'),

            company_name=data.get('company_name'),
            contact_name=data.get('contact_name'),
            landline=data.get('landline'),
            mobile=data.get('mobile'),
            email=data.get('email'),
            # certifications=data.get('certifications'),
            # specifications=data.get('specifications'),
            identifier=data.get('identifier'),
            format=data.get('format'),
            comments=data.get('comments'),
    
            departure_address_lat=data.get('departure_address_lat', None),
            departure_address_lng=data.get('departure_address_lng', None),
            destination_address_lat=data.get('destination_address_lat', None) if data.get('destination_address_lat', None) else None,
            destination_address_lng=data.get('destination_address_lng', None) if data.get('destination_address_lng', None) else None,
    
            weight_of_full_truck=data.get('weight_of_full_truck') if data.get('weight_of_full_truck') else None,
            price=data.get('price'),
        )

        price_data = calculate_price_from_sales(data)

        supplier.price_exwb = price_data['exwb']
        supplier.price_exws = price_data['exws']

        supplier.save()

        SupplierPrices.objects.create(
            added_by=self.request.user,
            suppliers=supplier,
            price_exwb=supplier.price_exwb,
            price_exws=supplier.price_exws
        )

        for certification_document in request.FILES.getlist('certifications'):
            CertificationDocumentSuppliers.objects.create(
                supplier=supplier,
                file=certification_document
            )

        for specification_document in request.FILES.getlist('specifications'):
            SpecificationDocumentSuppliers.objects.create(
                supplier=supplier,
                file=specification_document
            )

        generate_offers_for_new_supplier(supplier)

        return redirect('suppliers:list')


class SuppliereNewPriceCreateView(View):
    
    def get(self, request, pk):
        if not request.user.is_authenticated:
            print("Not Logged In")
            return redirect("accounts:login")

        supplier = Suppliers.objects.get(id=pk)
        return render(request, "suppliers/source/price.html", {
            "supplier": supplier
        })

    def post(self, request, pk):
        print(request.POST)
        supplier = Suppliers.objects.get(id=pk)

        price_data = calculate_price_from_source({
            "price_type": request.POST.get("price_type"),
            "margin": supplier.product.default_margin,
            "departure_address_lat": supplier.departure_address_lat,
            "departure_address_lng": supplier.departure_address_lng,
            "destination_address_lat": request.POST.get('destination_address_lat', None),
            "destination_address_lng": request.POST.get('destination_address_lng', None),
            "price": int(request.POST.get('price')),
            "weight_of_full_truck": request.POST.get('weight_of_full_truck', None),
            "region": supplier.region.id,

        })

        supplier.price_exwb = price_data['exwb']
        supplier.price_exws = price_data['exws']

        supplier.save()

        SupplierPrices.objects.create(
            added_by=self.request.user,
            suppliers=supplier,
            price_exwb=price_data['exwb'],
            price_exws=price_data['exws']
        )

        generate_offers_for_supplier_new_price(supplier)

        return redirect("suppliers:list")


class SupplierUpdateView(View):
    
    def get(self, request, pk):
        if not request.user.is_authenticated:
            print("Not Logged In")
            return redirect("accounts:login")

        supplier = Suppliers.objects.get(id=pk)
        supplier_prices = supplier.get_supplier_prices()
        return render(request, 'suppliers/update.html', {
            "supplier": supplier,
            "supplier_prices": supplier_prices
        })

    def post(self, request, pk):
        supplier = Suppliers.objects.get(id=pk)

        supplier.company_name = request.POST.get('company_name')
        supplier.contact_name = request.POST.get('contact_name')
        supplier.landline = request.POST.get('landline')
        supplier.mobile = request.POST.get('mobile')
        supplier.email = request.POST.get('email')
        supplier.identifier = request.POST.get('identifier')
        supplier.format = request.POST.get('format')

templates/suppliers/closest_region.html
function get_closest_region() {
    // URL of the API endpoint
    const apiUrl = '{% url "countries:api_closest_region" %}';
    $.ajax({
        url: apiUrl,
        headers: {
          // 'Content-Type': 'application/json',
          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
        },
        data: {
            lat: document.getElementById('input_departure_address_lat').value,
            lng: document.getElementById('input_departure_address_lng').value
        },
        type: 'POST',
        success: function(res) {
            console.log(res)
            document.getElementById('input_region').value = res.region_id
            $("#input_transportational_cost").val(region_data[res.region_id]['price']);
        },
        error: function(error) {
            console.log(error);
        }
    })
}

templates/suppliers/delete.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <form action="" method="post">{% csrf_token %}
        <h1 class="mt-3 ">Are you sure you want to delete this Supplier [{{supplier.company_name}}, {{supplier.contact_name}}]?</h1>
        <button class="btn btn-danger px-3">Yes</button>
        <a class='btn btn-primary px-3' href="{% url 'products:list' %}">No</a>
        
    </form>
</div>
{% endblock body %}

templates/suppliers/list.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <h1 class="text-center">Liste of suppliers</h1>
    {% if request.user.is_superuser %}
    <h1><a class='btn btn-success text-center col-12' href="{% url 'suppliers:create_by_sourcing' %}">Create Suppliers(Sourcing)</a></h1>
    <h1><a style='background-color: purple;' class='btn btn-success text-center col-12' href="{% url 'suppliers:create_by_sales' %}">Create Suppliers(Sales)</a></h1>
    {% elif request.user.team == 'sourcing' %}
    <h1><a class='btn btn-success text-center col-12' href="{% url 'suppliers:create_by_sourcing' %}">Create Suppliers(Sourcing)</a></h1>
    {% elif request.user.team == 'sales' %}
    <h1><a class='btn btn-success text-center col-12' href="{% url 'suppliers:create_by_sales' %}">Create Suppliers(Sales)</a></h1>
    {% endif %}
    <hr>
    <form action="." method="get">
        <div class="form-row align-items-center">
            <div class="col-5">
                <input type="text" class="form-control" id="searhInput" name="search" placeholder="Search By Supplier Company Name, Contact Name, Identifier" value="{{search}}">
            </div>
            <div class="col-3">
                <label class="sr-only" for="search">Product</label>
                <select name='product' id="input_product" class="form-control">
                    <option value>All Products</option>
                    {% if selected_product %}
                        <option selected value="{{selected_product.id}}">{{selected_product.name}}</option>
                    {% endif %}
                    {% for product in products %}
                        <option value="{{product.id}}">{{product.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-3">
                <label class="sr-only" for="search">Country</label>
                <select name='country' id="input_country" class="form-control">
                    <option value>All Countries</option>
                    {% if selected_country %}
                        <option selected value="{{selected_country.id}}">{{selected_country.name.title}}</option>
                    {% endif %}
                    {% for country in countries %}
                        <option value="{{country.id}}">{{country.name.title}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-1">
                <button type="submit" class="btn btn-primary col-12">Search</button>
            </div>
        </div>
    </form>
    <hr>
    {%for supplier in suppliers %}
    <div class="col-12 mb-5">
        <div class="media">
            <div class="media-body px-3">
                <h1 class="font-weight-bold">{{supplier.company_name}} ({{supplier.contact_name}}) - {{supplier.product.name}}</h1>
                <h6 class="">Contact: {{supplier.landline}}, {{supplier.mobile}}, {{supplier.email}}</h6>
                <h6 class="">Location: {{supplier.region.name}}, {{supplier.region.country.name.title}}</h6>
                <h6 class="">Margin: {{supplier.margin}}</h6>
                <h6 class="">Price[EXWB]: {{supplier.price_exwb|floatformat:2}}, ({{supplier.supplier_prices.last.added_on.date}})</h6>
                <h6 class="">Price[EXWS]: {{supplier.price_exws|floatformat:2}}, ({{supplier.supplier_prices.last.added_on.date}})</h6>
                <h6 class="">Added By: {{supplier.added_by.username}} ({{supplier.added_by.team}})</h6>
            </div>
            <div class="align-self-center">
                <a type="button" href="{% url 'suppliers:add_price_by_sourcing' supplier.id %}" class="btn btn-primary font-weight-bold mb-1 col-12"><b>Add Price</b></a>
                    <a type="button" href="{% url 'suppliers:update' supplier.id %}" class="btn btn-warning font-weight-bold mb-1 col-12"><b>Edit</b></a><br>
                    <a type="button" href="{% url 'suppliers:delete' supplier.id %}" class="btn btn-danger font-weight-bold mb-1 col-12"><b>Delete</b></a><br>
            </div>
        </div>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock body %}

templates/suppliers/update.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
     <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>

<style>
  #map {
    height: 300px;
    width: 100%;
  }
</style>
{% endblock css %}

{% block body %} 
<div class="container mt-3">
    <form action="" method="post">{% csrf_token %}
        <h1 class="text-center">Edit Supplier</h1><hr>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="input_company_name">Company Name</label>
                <input required type="text" class="form-control" name='company_name' id="input_company_name" placeholder="" value="{{supplier.company_name}}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="input_contact_name">Contact Name</label>
                <input required type="text" class="form-control" name="contact_name" id="input_contact_name" placeholder="" value="{{supplier.contact_name}}" required>
            </div>
            <div class="form-group col-md-4">
                <label for="input_landline">Landline</label>
                <input type="text" class="form-control" name="landline" id="input_landline" placeholder="" value="{{supplier.landline}}">
            </div>
            <div class="form-group col-md-4">
                <label for="input_mobile">Mobile</label>
                <input type="text" class="form-control" name="mobile" id="input_mobile" placeholder="" value="{{supplier.mobile}}">
            </div>
            <div class="form-group col-md-4">
                <label for="input_email">Email</label>
                <input type="email" class="form-control" name="email" id="input_email" placeholder="" value="{{supplier.email}}">
            </div>
            <div class="form-group col-md-5">
              <label for="input_identifier">Identifier</label>
              <input type="text" class="form-control" name="identifier" id="input_identifier" placeholder="" value="{{supplier.identifier}}">
          </div>
          <div class="form-group col-md-7">
              <label for="input_format">Format</label>
              <input type="text" class="form-control" name="format" id="input_format" placeholder="" value="{{supplier.format}}">
          </div>
            <div class="form-group col-md-12">
                <label for="input_comments">Comments</label>
                <textarea class='form-control' id="input_comments" name="comments" rows="4" cols="50"></textarea>
            </div>
            <div class="form-row col-12">
                <div class="form-group col-md-6">
                  <div class="form-row row">
                  <label for="input_price" class="col-12">Buying Price(EXWB)</label>
                    <input required type="number" class="form-control col-11" name="price" id="input_price" placeholder="" value="{{supplier.price_exwb|floatformat:2}}" disabled><span class="col-1 mt-2 text-bold text-lg">€</span>
                  </div>
                </div>
                <div class="form-group col-md-6">
                  <div class="form-row row">
                  <label for="input_price" class="col-12">Selling Price</label>
                    <input required type="number" class="form-control col-11" name="price" id="input_price" placeholder="" value="{{supplier.price_exws|floatformat:2}}" disabled><span class="col-1 mt-2 text-bold text-lg">€</span>
                  </div>
                </div>
                <div class="form-group col-md-6">
                  <div class="form-row row">
                  <label for="input_price" class="col-12">Product Margin</label>
                    <input required type="number" class="form-control col-11" name="price" id="input_price" placeholder="" value="{{supplier.product.default_margin|floatformat:2}}" disabled></span>
                  </div>
              </div>
                <div class="form-group col-md-6">
                  <div class="form-row row">
                  <label for="input_price" class="col-12">Weight Of Full Truck</label>
                    <input required type="number" class="form-control col-11" name="price" id="input_price" placeholder="" value="{{supplier.weight_of_full_truck|floatformat:2}}" disabled></span>
                  </div>
              </div>
                <div class="form-row col-12">
                    <div id="map">
                    </div>
                </div>
          <hr>
          <div class="form-row col-12">
            <div class="form-group col-md-6">
              <label for="input_certifications">Certifications</label>
              {% for certification in offer.supplier.certifications.all %}
                <br><a href="{{certification.file.url}}">{{certification.file.name}}</a>
              {% endfor %}
            </div>
            <div class="form-group col-md-6">
              <label for="input_specifications">Specifications</label>
                {% for specification in offer.supplier.specifications.all %}
                <br><a href="{{specification.file.url}}">{{specification.file.name}}</a>
              {% endfor %}
            </div>
          </div>
          <hr>
        </div>
        {% if supplier_prices %}
        <h2 class="text-center">Price History</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Added By</th>
              <th scope="col">Selling Price</th>
              <th scope="col">Buying Price</th>
            </tr>
          </thead>
          <tbody>
              {% for prices in supplier_prices %}
              <tr>
                <td>{{prices.added_on.date}}</td>
                <td>{{prices.added_by.username}}</td>
                <td>{{prices.price_exws|floatformat:2}}</td>
                <td>{{prices.price_exwb|floatformat:2}}</td>
              </tr>
              {% endfor %}
            
          </tbody>
        </table>
        {% endif %}
          </div>
          <div class="col-12"> <button class="btn btn-primary col-12">Save</button></div>
        </div>
    </form>
</div>
{% endblock body %}

{% block js %}
<script>
    var departure_address_icon = L.icon({
    iconUrl: '{% static "markers/departure.png" %}',
    });
  
    var map = L.map('map').setView([0, 0], 2);
    L.tileLayer('https://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var marker_departure = L.marker([
      {{supplier.departure_address_lat}}, {{supplier.departure_address_lng}}
    ], {icon: departure_address_icon}).bindPopup("Departure").addTo(map);

    groups = L.featureGroup([marker_departure, marker_departure]);
    map.fitBounds(groups.getBounds());
    console.log("MAPS")
  
</script>
{% endblock js %}